<문제 1>

삼각형의 높이 N을 입력받아서 아래와 같이 문자 'A'부터 차례대로 왼쪽 대각선으로 채워서 삼각형 모양을 출력하는 프로그램을 작성하시오.

< 처리조건 > 

1. 오른쪽 위부터 왼쪽 아래쪽으로 이동하면서 문자 'A'부터 차례대로 채워나간다.
2. N번 행까지 채워지면 다시 오른쪽 둘째 행부터 왼쪽 아래로 채워나간다.
3. 삼각형이 모두 채워질 때까지 반복하면서 채워 나간다. (문자 'Z'다음에는 'A'부터 다시 시작한다.)

< 입력형식 >

삼각형의 높이 N(N의 범위는 100 이하의 양의 정수)을 입력받는다.

< 출력형식 >

주어진 형태대로 높이가 N인 문자삼각형을 출력한다. 문자 사이는 한 개의 공백으로 구분한다.

< 입력 예 >
```python
5
```

< 출력 예 >
```python
        A 
      B F 
    C G J 
  D H K M 
E I L N O
```

< 출제의도 >

1. 아스키코드를 적용할 줄 아는가
2. 연산자를 잘 활용하는가
3. 반복문을 효율적으로 쓰는가
`

< 출제의도 >

1. 아스키코드를 적용할 줄 아는가
2. 연산자를 잘 활용하는가
3. 반복문을 효율적으로 쓰는가
4. 알고리즘을 얼마나 효율적으로 짜는가

< 문제 2 >

n개의 정수를 입력받아서 최대공약수와 최소공배수를 구하는 프로그램을 수업시간에 배운대로 <i><b> 무조건 함수를 효율적으로 구성해서 </b></i> 작성하여 보자.

< 입력 형식 >

1. 첫째 줄에 N (2≤N≤10) 을 입력 받고 다음 줄에 N개의 정수를 공백으로 구분하여 입력 받는다.
2. 입력 받는 정수는 2이상 10.000 이하이다. 데이터의 크기가 주어진 범위를 벗어나는 입력은 없다.

< 출력 형식 >

1. 입력받은 정수들의 최대공약수와 최소공배수를 공백으로 구분하여 출력한다.
2. 최소공배수는 20억 이하의 정수이다.

< 입력 예 >
```python
3
2 8 10
````

< 출력 예 >

```python
2 40
````

< 출제의도 >

1. 연산자를 잘 활용하는가
2. 조건문을 활용하는가
3. 함수를 얼마나 효율적으로 짜는가 (최소공약수를 다루는 함수, 최대공약수를 다루는 함수, or etc)

< 문제 3 >

양의 정수를 입력받아 역으로 보여주고 각 자리 숫자의 합을 구하는 프로그램을 수업시간에 배운대로 <i><b> 무조건 함수를 효율적으로 구성해서 </b></i> 작성하여 보자.

< 입력 형식 >

1. 21억 이하의 양의 정수를 입력받는다. 잘못된 데이터는 입력되지 않는다. 
2. 하나의 결과가 나온 후에도 계속 새로운 입력을 받다가 0이 입력되면 프로그램을 종료한다.
3. 최대 10개의 양의 정수가 입력될 수 있다.

< 출력 형식 >

1. 입력받은 수의 역과 각 자리 숫자의 합을 공백으로 구분하여 출력한다.
2. 유효하지않은 "0"은 출력하지 않는다. 
3. 입력받은 수의 역도 21억 이하의 정수이다.

< 입력 예 >
```python
453
123456
0
```
< 출력 예 >
```python
354 12
654321 21
```

< 문제 4 >

임의의 문장을 입력받아 각 단어별로 나눈 후에 단어들의 중복되는 개수를 구하는 프로그램을 수업시간에 배운대로 <i><b> 무조건 함수를 효율적으로 구성해서 </b></i> 작성하여 보자.

< 처리조건 >

1. 입력된 스트링은 글자의 제한은 없다. 즉, 알파벳 대.소문자, 공백, ', ' 등도 입력으로 들어 올 수 있다. 
2. 입력된 문장에서 각 단어사이의 구분은 공백으로 한다. 
3. 단어에는 공백을 제외한 모든 문자들이 포함된다.​ 

< 입력 형식 >

1. 임의의 문장을 입력받는다.(문장의 길이는 200 이하)
2. 하나의 결과가 나온 후에도 계속 새로운 입력을 받다가, "END"가 입력되면 프로그램을 종료한다. (문장의 개수를 30을 넘지 않는다.)

< 출력 형식 >

각 문장 단위로 단어들의 발생 빈도를 오름차순 크기(아스키코드)순으로 출력한다.

< 입력 예 >

```python
I AM DOG DOG DOG DOG A AM I
I AM OLYMPIAD JUNGOL JUNGOL OLYMPIAD
END
```

< 출력 예 >

```python
354 12
654321 21
A : 1
AM : 2
DOG : 4
I : 2 
AM : 1 
I : 1 
JUNGOL : 2
OLYMPIAD : 2